### ISSUE TITLE
Missing IAM Role Policies

### ISSUE THREAD

**Issue by amybachir** [argoflow/argoflow-aws#126]
I noticed the following IAM role policies are missing from https://github.com/argoflow/argoflow-aws/tree/master/docs/iam_policies:

- oauth2_proxy
- kubeflow_pipelines
- cert-manager
- kube2iam_pipelines

**Comment by soleares** [comment]
Agree, this needs to be updated in the README.

From what I understand, the following are for experimental features that don't work yet and are disabled in kustomization.yaml so you shouldn't need to set them up.
- kubeflow_pipelines
- kube2iam_pipelines

I used this policy for cert-manager but with the specific hosted zone id in the second statement. I'm not 100% sure it's working yet, but that's what's recommended from the cert-manager repo.
- https://cert-manager.io/docs/configuration/acme/dns01/route53/#set-up-an-iam-role

I'm not aware of any required permissions in oauth2_proxy. I add "elasticache:*" for the redis cluster arn but I don't think it's needed since it's just making a TCP connection to redis.

**Comment by EKami** [comment]
Same issue here, the main issue I have is for the `oauth2_proxy` role, no idea what permission it needs

**Comment by soleares** [comment]
I would personally start with no permissions for this role and then if it’s not working it will tell you in the logs if it needs something additional.

**Comment by karlschriek** [comment]
The missing policies were added with https://github.com/argoflow/argoflow-aws/pull/159

The oauth2-proxy Pod needs access to an ExternalSecret for the Client ID and Client Secret of the OIDC application. The policy for this is described here: https://github.com/argoflow/argoflow-aws/blob/master/docs/iam_policies/external-secrets_auth.json
