### ISSUE TITLE
Current Kiali configuration isn't working

### ISSUE THREAD

**Issue by soleares** [argoflow/argoflow-aws#166]
Has anyone gotten Kiali to work?

- When I enable Kiali and try to access it, it throws an RBAC error in the UI.
- The current operator configuration doesn't look correct because it tries to setup an ingress for `kiali.example.com`: https://github.com/argoflow/argoflow-aws/blob/master/distribution/argocd-applications/kiali.yaml#L28-L39

**Comment by DavidSpek** [comment]
I have Kiali working, but it is still in the kfserving feature branch as I was using it to debug KNative and KFServing. Same thing goes for Jaeger.
Note: I've moved Kiali to the monitoring namespace as a test so it could pickup on the Grafana secret. Another difference it to use Istio to route to Kiali instead of an ingress, since the ingress configuration was being annoying and Istio was easier to setup. You should also check changes in the monitoring-resources directory.

https://github.com/argoflow/argoflow-aws/blob/feature/kfserving-testing/distribution/argocd-applications/kiali.yaml
https://github.com/argoflow/argoflow-aws/tree/feature/kfserving-testing/distribution/monitoring-resources

**Comment by soleares** [comment]
Thanks @DavidSpek. That's helpful and should give me what I need to get it working. Do you have a plan yet for the grafana secret? Will you duplicate it in both namespaces or move grafana into the monitoring namespace?

**Comment by DavidSpek** [comment]
What I've done now is move Kiali to the monitoring namespace. I think that's what you meant :). I'm actually busy rewriting the actual manifests to improve the Istio implementation and the usefulness of Kiali.

**Comment by soleares** [comment]
Ah yes, that's what I meant :) I won't need this right away until so I'll let you continue and check in on it in a few weeks. Thanks again!
